### ISSUE TITLE
Getting This Error Pls Reply Fast As You can I realy need

### ISSUE THREAD

**Issue by GoodGamerType776** [JOY6IX9INE/OperaGX-Promo-Gen#1]
![image](https://github.com/JOY6IX9INE/OperaGX-Promo-Gen/assets/138398684/f8092fc5-6037-43d1-bd39-08b964729343)

**Comment by JOY6IX9INE** [comment]
Clear the proxy file and make sure it do not have more then 1 empty line.

**Comment by silverloins** [comment]
I am getting same issue can you help?
